name: dart2_constant
version: 1.0.0-dev
description: A polyfill for Dart 2 constant names.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/dart2_constants

environment:
  sdk: '>=1.24.0 <2.0.0'
